#!/bin/bash

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}🚀 Starting FreelanceFlow Setup...${NC}"

# 1. Start Database via Docker (Port 5433 to avoid conflicts)
echo -e "${YELLOW}📦 Starting Database Container...${NC}"
if ! docker compose up -d postgres; then
    echo -e "${RED}❌ Failed to start Docker. Make sure Docker is running.${NC}"
    exit 1
fi

# Wait for DB to be ready
echo -e "${YELLOW}⏳ Waiting for Database to be ready...${NC}"
sleep 5

# 1.5 Ensure Database Exists
echo -e "${YELLOW}📦 Ensuring Database 'mockmate_dev' exists...${NC}"
docker exec interview-engine-postgres-1 createdb -U postgres mockmate_dev || echo "Database might already exist, continuing..."

# 2. Configure .env
echo -e "${YELLOW}⚙️  Configuring Environment...${NC}"
cat > .env << EOL
# Auto-generated by start.sh
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=mockmate_dev
POSTGRES_PORT=5433

# Connect to Docker DB on localhost:5433
DATABASE_URL=postgresql://postgres:postgres@localhost:5433/mockmate_dev

# App Configuration
PORT=5173
HOST=0.0.0.0
NODE_ENV=development

# Secrets (Default for dev)
SESSION_SECRET=dev_secret_key_change_in_prod
GEMINI_API_KEY=AIzaSyAdUFqoIu-HFnL1fjsNpgAboLkW95pY-ek
EOL

# 3. Install Dependencies
echo -e "${YELLOW}npm installing dependencies...${NC}"
npm install

# 4. Seed Database
echo -e "${YELLOW}🌱 Seeding Database (Creating Admin User)...${NC}"
npm run seed

# 5. Start App
echo -e "${GREEN}✅ Setup Complete! Starting App...${NC}"
echo -e "${GREEN}👉 Access at: http://localhost:5173 or http://YOUR_PUBLIC_IP:5173${NC}"
echo -e "${GREEN}👉 Login: admin / admin123${NC}"

npm run dev
